### ISSUE TITLE
Implement Webcast grabbing from Panopto

### ISSUE THREAD

**Issue by TomatoCream** [goweiwen/ivle-sync#1]
Ding feng here

**Comment by TomatoCream** [comment]
I wan add some webcast grabbing

**Comment by goweiwen** [comment]
An example MP4 link returned from the API is 
https://fac.weblecture.nus.edu.sg/Panopto/Podcast/StreamInBrowser/e658fcb9-2301-4761-8a3c-165792fe6326.mp4?mediaTargetType=videoPodcast

In order to access it without a 403 response, Panopto requires authentication.

By signing in at https://fac.weblecture.nus.edu.sg/Panopto/Pages/Auth/Login.aspx?instance=nus first, we can receive an authentication cookie (.ASPXAUTH).

Passing this along with the GET request will let us download the MP4.
